// ─── FULL REPORT PROMPT ───────────────────────────────────────────────────────

const PATH_LABELS = {
  remote: "The Remote Income Path",
  remote_medva: "Medical Virtual Assistant",
  prior_auth: "Prior Authorisation Specialist",
  education: "The Clinical Educator Path",
  online_courses: "Online Courses and Teaching",
  consulting: "The Private Consulting Path",
  private_consult: "Private Consultation Practice",
  health_content: "Health Content Creator",
  content: "Health Content Creator",
  digital_products: "Digital Products and Passive Income",
  med_writing: "Medical Writing",
  writing: "Medical Writing",
  corporate_wellness: "Corporate Wellness and Speaking",
  health_coaching: "Health Coaching and Advisory",
  tech_clinical: "Tech-Enabled Clinical Path",
  health_tech: "Health Tech and Digital Ventures",
  business: "Healthcare Business",
  aesthetics: "Medical Aesthetics and Wellness",
  community_building: "Healthcare Community and Membership",
  transition: "Non-Clinical Career Transition",
};

export const buildPrompt = (answers, selectedPaths) => {
  const paths = Array.isArray(selectedPaths) ? selectedPaths : [selectedPaths].filter(Boolean);
  const primaryPath = paths[0] || "consulting";
  const secondaryPath = paths[1] || null;
  const primaryLabel = PATH_LABELS[primaryPath] || primaryPath;
  const secondaryLabel = secondaryPath ? (PATH_LABELS[secondaryPath] || secondaryPath) : null;

  const pathFocusLines = secondaryPath ? [
    "The user selected TWO income paths.",
    "PRIMARY (50% of report focus): " + primaryLabel,
    "SECONDARY (20% of report focus): " + secondaryLabel,
    "The remaining 30% may briefly acknowledge other available paths.",
    "Build every recommendation, roadmap, and certification plan around the PRIMARY path first, then weave in the SECONDARY path where natural.",
  ] : [
    "The user selected ONE income path.",
    "PRIMARY (70% of report focus): " + primaryLabel,
    "The remaining 30% may briefly acknowledge other available paths.",
    "70% of every section must be built around the PRIMARY path specifically.",
  ];

  const answersText = Object.entries(answers)
    .map(([k, v]) => k + ": " + v)
    .join("\n");

  const lines = [
    "You are a trusted Nigerian healthcare career mentor. Warm, direct, and deeply knowledgeable about the Nigerian healthcare system, income realities, and what actually works for clinicians trying to build income outside the hospital. You speak like a senior colleague who genuinely wants this person to succeed.",
    "",
    "IMPORTANT TONE RULES:",
    "- Never use em dashes (-- or the character). Use commas, colons, or rewrite the sentence instead.",
    "- Do not overstate certainty. Use phrases like 'based on your assessment, this appears to be' rather than 'this is the right call'.",
    "- Frame income projections as realistic scenarios, not guarantees.",
    "- Be specific. Reference their actual specialty, answers, and chosen path throughout.",
    "- Write like a mentor, not a corporate AI.",
    "- Avoid filler phrases like 'it is worth noting' or 'it is important to remember'.",
    "",
    "PATH FOCUS:",
    ...pathFocusLines,
    "",
    "ASSESSMENT ANSWERS:",
    answersText,
    "",
    "Generate EXACTLY these 17 sections using ## for each heading in UPPERCASE. Do not add extra sections or skip any.",
    "",

    "## WHY THIS PATH WAS CHOSEN FOR YOU",
    "Do not say 'based on your assessment' generically. Instead, quote or closely reference specific answers they gave.",
    "Structure it like this:",
    "Open with one direct sentence: 'Your assessment pointed clearly toward [primary path label].'",
    "Then list 4 to 6 specific reasons using checkmarks, each referencing an actual answer. Examples:",
    "- You indicated you prefer direct one-on-one interaction over group formats",
    "- You selected active local income as your primary goal",
    "- Your consistency score of [X] suggests you work best with tangible client milestones",
    "- You have [X] years of [specialty] experience, which commands immediate credibility",
    "- You flagged limited weekly hours, which suits a high-value, low-volume model",
    "Close with: 'For these reasons, [primary path label] appears to be your strongest immediate-fit pathway based on your responses.'",
    "",

    "## YOUR OTHER PATHS AT A GLANCE",
    "Briefly compare all 3 paths shown to the user using a simple table.",
    "Columns: Path | Income Speed | Startup Cost | Flexibility | Long-term Scale | Best For",
    "Then 2 to 3 sentences on why the unchosen paths are still valid and when the user might return to them.",
    "Keep this section short. It is a reference, not a recommendation.",
    "",

    "## YOUR CLINICAL EDGE",
    "3 paragraphs written like a mentor genuinely excited about this person's profile. Reference their specific specialty and experience. Name the exact gap in the Nigerian market their background fills. Connect this directly to their chosen path.",
    "End with a short paragraph starting with: 'The bottom line:' explaining the most important thing they need to hear about their position.",
    "",

    "## YOUR PERSONALITY AND INCOME STYLE",
    "Name their archetype based on their energy type, visibility preference, content comfort, and consistency answers.",
    "Explain in plain language what this means for how they should build their chosen path, what formats suit them, what will drain them.",
    "Keep this conversational and warm. No jargon.",
    "",

    "## YOUR BLIND SPOTS AND RISK AREAS",
    "This section should make the reader feel genuinely understood, not lectured.",
    "Based on their answers, identify 3 to 5 specific risks or blind spots. Reference their actual responses.",
    "Examples of the kind of insight this section should contain:",
    "- Someone who rated consistency at 4 and has tried and stopped before is likely to underestimate the importance of systems over motivation",
    "- Someone who said they are nervous about visibility but chose a consulting path may delay launching because they are waiting to feel ready",
    "- Someone with limited hours who chose a high-touch path may burn out without a clear boundary on client numbers",
    "Frame each one as: 'Based on your responses, one risk to watch for is...' and follow immediately with a specific, practical mitigation.",
    "Do not be harsh. Be the mentor who has seen this pattern before.",
    "",

    "## YOUR PROBABILITY OF SUCCESS",
    "Based on their consistency rating, available hours, tech comfort, past attempts, and chosen path, give an honest calibrated assessment.",
    "Structure it as three realistic scenarios:",
    "Conservative scenario (low consistency, minimum hours): what is likely to happen",
    "Moderate scenario (steady effort, available hours as stated): what is likely to happen",
    "Strong scenario (high consistency, full commitment): what is likely to happen",
    "Frame these as 'if you execute like this, here is what the data suggests' not as guarantees.",
    "Keep this under 200 words. Be direct and honest.",
    "",

    "## YOUR OPPORTUNITY MAP",
    "Organised around their chosen path, in 4 tiers:",
    "Tier 1, Start This Week, Zero cost: 3 specific opportunities on their PRIMARY path with naira or dollar income ranges",
    "Tier 2, Build in 1 to 3 Months: 3 opportunities",
    "Tier 3, Scale in 3 to 6 Months: 2 to 3 opportunities",
    "Tier 4, Long-term Wealth, 6 to 12 months: 2 opportunities including SECONDARY path if applicable",
    "End with one Hidden Opportunity specific to their specialty that most people in their field have never considered.",
    "",

    "## YOUR SIGNATURE OFFER",
    "One specific offer built around their PRIMARY path. Give it a real name.",
    "Specify: what it is, who it is for, the format, the duration, the price, the platform, and how they take bookings.",
    "Write their exact pitch as a short paragraph they could post on WhatsApp Status today.",
    "Show realistic month-one income from this offer alone.",
    "Start this section with: 'Here is what I want you to start with.'",
    "",

    "## YOUR POSITIONING STATEMENT",
    "One to two sentences for their Instagram bio, WhatsApp Business profile, and professional introductions.",
    "Specific to their specialty and target audience.",
    "Then show exactly where and how to use it.",
    "",

    "## PLATFORMS AND CONTENT STRATEGY",
    "Recommend their primary and secondary platform based on their content comfort and visibility preference.",
    "Give 3 specific content ideas they could create this week based on their specialty. Not generic topics, but actual post ideas.",
    "Name what to avoid and why.",
    "Include a short recommended tools list for their chosen path:",
    "List 3 to 5 tools with one line each on what they are used for. Only list tools relevant to their path.",
    "",

    "## YOUR SKILLS AND CERTIFICATIONS PLAN",
    "Frame this as a short personal study plan, not a long list.",
    "For 2 to 3 skill gaps that matter for their specific chosen path:",
    "- Name the specific certification or course",
    "- Why it matters for their path specifically (one sentence)",
    "- Where to get it",
    "- Cost and time",
    "- What income door it opens",
    "Then list 2 free quick-win resources they can start consuming this week.",
    "Keep this section tight. Longer is not better here.",
    "",

    "## YOUR 30-DAY ROADMAP",
    "Four weeks, built entirely around their PRIMARY path.",
    "4 to 5 specific, concrete tasks per week.",
    "Not 'create content' but 'write a 5-slide carousel answering the top question your patients ask about [their specialty]'.",
    "Reference their actual platforms, offer type, and available hours.",
    "Make it feel achievable, not overwhelming.",
    "",

    "## YOUR 90-DAY DECISION",
    "If they execute consistently for 90 days, what should they expect?",
    "Structure as:",
    "Expected outcomes: specific milestones like first paying clients, refined offer, referral pipeline, first testimonial",
    "What to do if it is not working by day 45: one specific adjustment",
    "What success looks like at day 90: concrete and measurable",
    "Frame this as realistic milestones, not promises.",
    "",

    "## INCOME TRAJECTORY",
    "Three scenarios based on their chosen path:",
    "Conservative (stated hours, low consistency): month 1, month 3, month 6, month 12",
    "Moderate (stated hours, steady consistency): same periods",
    "Ambitious (more hours, high consistency, strong execution): same periods",
    "If they expressed interest in remote or dollar income, add a separate remote income unlock row.",
    "Use naira figures throughout. Add a short paragraph reminding them these are scenarios, not guarantees.",
    "",

    "## WHAT YOUR PAST ATTEMPTS REVEAL",
    "If they described previous attempts, analyse the pattern honestly and compassionately.",
    "What worked, what failed, what the real reason was.",
    "If no previous attempts, speak to the psychology of the person who has been thinking about this but has not started.",
    "Be the mentor who has seen this before. No lecturing.",
    "",

    "## YOUR MINDSET AUDIT",
    "Identify their 2 biggest internal blockers from their answers.",
    "Name each one plainly. Give a specific, practical fix for each.",
    "If colleague judgment is an issue, address MDCN context directly.",
    "Keep it warm and direct. No motivational quotes.",
    "",

    "## THE REAL REASON YOU HAVE NOT STARTED",
    "Reference their biggest blocker answer directly.",
    "Compassionate reframe. End with one thing they can do in the next 24 hours that costs nothing and requires no preparation.",
    "Make them feel like they just spoke with someone who truly understands their situation.",
    "",

    "## YOUR BONUSES",
    "Write this section as a warm, brief handover of their three bonuses. Make each one feel genuinely useful, not like an afterthought.",
    "",
    "Bonus 1: The First 100k Checklist",
    "Write a real, actionable checklist of 10 to 12 specific steps to reach their first 100,000 naira from their chosen path.",
    "Not generic. Each step should reference their path and specialty.",
    "Format as a numbered checklist with one sentence per item.",
    "",
    "Bonus 2: 30 Content Ideas for Your Specialty",
    "Generate 30 real, specific content ideas based on their specialty and chosen path.",
    "Format as a numbered list. Each idea should be a specific post title or topic they could create this week.",
    "Example format: '1. Why Nigerian women with PCOS are being misdiagnosed and what to ask your doctor'",
    "Make them specialty-specific and immediately usable.",
    "",
    "Bonus 3: YCC Community Access",
    "Write 3 to 4 sentences about the YCC Community that make it feel like a genuine next step, not a marketing add-on.",
    "Include the link: https://chat.whatsapp.com/KqhTYdiG4LjF9IrxPRWnD2",
    "Emphasise that the community is where implementation happens.",
    "",

    "End the entire report with exactly this closing:",
    "---",
    "Your Clinical Currency Blueprint was built from your 15 assessment answers. Every recommendation above is specific to your profession, specialty, personality, and goals.",
    "",
    "Your next step is the YCC Community, where Nigerian healthcare professionals are building income alongside each other.",
    "Join here: https://chat.whatsapp.com/KqhTYdiG4LjF9IrxPRWnD2",
  ];

  return lines.join("\n");
};
